Moved writing and reading DTO from Packet into DTO classes.
CRPE-Team/MiNET pull request #5
Opened 2023-11-07 20:46 UTC by thehills1

2023-12-07 14:24 UTC, DarkLexFirst requested changes

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET.Client/MiNetClient.cs
> +		}
Включи отображение пробелов в диффах. Поправь это.

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/Utils/ItemStack.cs
Пройдись пж по чек листу:

- [ ] корректно работает creative inventory
- [ ] все наши UInv работает корректно
- [ ] перемещение предметов по инвентарю работает корректно
- [ ] выбрасывание и подбирание работает корректно (проверить и блоки и предметы
- [ ] с блоков выпадает корректный дроп
- [ ] работает ведро (хотя бы с водой)
- [ ] работает установка блоков, которые в инвентаре отображаются как предметы (тростник, костер, кровать)

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/Utils/EnchantOptions.cs
проверь, что выдаются предметы с корректными энчантами
(у нас была тестовая команда, позволяющая зачаровать предмет в руке)
Кроме этого был специальный пустой энчант (блок лобби, в котором находишься, или выбранной команды)
Не должно отображаться название энчанта, а сам блок должен переливаться

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/PlayerAttributes.cs
Пройтись по чек листу

- [ ] работают стенды (видны неймтеги, не видны энтити "части" голограммы)
- [ ] работает селектор режимов
- [ ] время не идет там, где это отключено (нет визуального, возможно дерганного, движения неба)

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/PlayerAttributes.cs
не понял, что тут делает Itemstates, его и все сопутствующее в отдельный файл бы

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/PlayerAttribute.cs
чек лист тот же, что и у [src/MiNET/MiNET/PlayerAttributes.cs](https://github.com/CRPE-Team/MiNET/pull/5/files#diff-c2ed2b876b89b350b2755aa8ba5943d93ae78aadd926e2593f2a307f04dfcba5)

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/Net/DimensionData.cs
в чистом майнете попробуй попаст в ад

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/Net/Crafting/Recipes.cs
попробуй скрафтить 
палку(в верстаке и инвентаре), 
сундук, 
верстак(в верстаке и инвентаре),
покрасить шерсть(в верстаке и инвентаре),
деревянный инструмент из разного типа досок,
торт

2023-12-07 14:24 UTC, DarkLexFirst commented on src/MiNET/MiNET/Net/AbilityLayers.cs
проверь, что на TNTRun работают двойные прыжки, и что на BlockParty нормально работает ускорение

2024-02-18 00:45 UTC, thehills1 commented on src/MiNET/MiNET/Net/AbilityLayers.cs
перенес (pt 6)

2024-02-18 11:52 UTC, thehills1 commented on src/MiNET/MiNET/Net/Crafting/Recipes.cs
перенес (pt. 7)

2024-07-16 14:55 UTC, closed without merging